language: c

os:
    - osx

sudo: false

env:
    global:
        secure: "Ot7aKmwqgrfttGbliX2uR2QVhwxdXKIgGmZlsr/hfIkMZoaei1JzHsbfmrKuxocoQ/38Z8UZvDh6fSXCZKVGuDpEhb/PHeNuk7YPFXITyJWA9NyIrOh+xjrfLBSp7S/V33idReGVznuI4v/tB3PfZChmqgEns5z7BGZZaz5sIws="

addons:
    apt:
        packages:
            # UDUNITS2
            - texinfo
            # libmo_unpack
            - check
            # NCO
            - gfortran
            - antlr
            - g++
            - bison
            - flex
            - libantlr-dev
            - gsl-bin
            - libgsl0-dev

before_install:
    - brew update
    # Unit testing framework for C (used by libmo_unpack).
    - brew install check
    # NCO.
    - brew install gsl
    # https://travis-ci.org/ioos/conda-recipes/builds/67641190
    #- brew install antlr2

install:
    # Set the numpy variable. This isn't used, but conda-build complains if we haven't set it already.
    - export CONDA_NPY=19
    - wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
    - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
    - conda config --set show_channel_urls True
    - conda install obvious-ci --yes -c conda-forge

    - conda config --add channels ioos
    - python scripts/expand_source.py
    - obvci_install_conda_build_tools.py

script:
    - obvci_conda_build_dir ./ ioos --channel main --build-condition "numpy ==1.9" "python >=2.7,<3|>=3.4"
