name: IOOS
channels:
    - conda-forge
dependencies:
    - python=2.7
    - beautifulsoup4
    - cartopy
    - cc-plugin-glider
    - cmocean
    - compliance-checker
    - ctd
    - cython
    - descartes
    - fiona
    - folium
    - gdal
    - geojson
    - geojsonio
    - geopandas
    - geos
    - gridgeo
    - gsw
    - iris
    - jupyter
    - launcher
    - matplotlib
    - mpld3
    - mplleaflet
    - numpy
    - oceans
    - oct2py
    - owslib
    - paegan
    - pandas
    - proj.4
    - pygc
    - pyoos
    - pyproj
    - pysgrid
    - pyugrid
    - qrcode
    - rasterio
    - requests
    - rtree
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - statsmodels
    - sympy
    - xlrd
    - xray
    - yaml
