name: IOOS
channels:
    - ioos
dependencies:
    - python=2.7
    - beautifulsoup4
    - cartopy
    - cc-plugin-glider
    - cmocean
    - compliance-checker
    - ctd
    - cython
    - descartes
    - fiona
    - folium
    - gdal=1.11.3
    - geojson
    - geojsonio
    - geopandas
    - geos>=3.4.2
    - gsw
    - iris
    - jupyter
    - launcher
    - matplotlib
    - mpld3
    - mplleaflet
    - numpy
    - oceans
    - oct2py
    - owslib
    - paegan
    - paegan-transport
    - pandas
    - pip
    - proj.4
    - pyoos
    - pyproj
    - pysgrid
    - pyugrid
    - pywafo
    - qrcode
    - rasterio
    - rdflib
    - requests
    - rtree
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - statsmodels
    - sympy
    - utilities
    - xlrd
    - xray
    - yaml
